version: '3.2'

services:
  # MySQL DB
  mysql:
    environment:
      MYSQL_DATABASE: example_db
      MYSQL_USER: example_user
      MYSQL_PASSWORD: example_password
      MYSQL_ROOT_PASSWORD: mysql123
    image: mysql
    restart: always
    container_name: local_mysql
    ports:
      - "3306:3306"
